### ISSUE TITLE
Empty Theme: Templates reference wrong theme slug for header.html

### ISSUE THREAD

**Issue by justintadlock** [WordPress/theme-experiments#146]
`index.html` and `singular.html` reference the `emptytheme` slug:

```
<!-- wp:template-part {"slug":"header","theme":"emptytheme","tagName":"header"} /-->
```

This is not updated when the theme is generated through the command line tool to match the generated theme's slug.

**Comment by kjellr** [comment]
@justintadlock I think that was fixed this morning in #143. Can you confirm?

Thanks!

**Comment by justintadlock** [comment]
Looks like I pulled the repo just before this change went in.

But, there's still an issue with the slug.  Using `Test 1` (a two-word theme name), the slug has an underscore instead of hyphen:

```
<!-- wp:template-part {"slug":"header","theme":"test_1","tagName":"header"} /-->
```

**Comment by kjellr** [comment]
> Using Test 1 (a two-word theme name), the slug has an underscore instead of hyphen

Good catch, thanks! @MaggieCabrera or @pbking is that something you can take a look at?

**Comment by MaggieCabrera** [comment]
> > Using Test 1 (a two-word theme name), the slug has an underscore instead of hyphen
> 
> Good catch, thanks! @MaggieCabrera or @pbking is that something you can take a look at?

Yep, I will have a look!
